#!/usr/bin/env bash
# display info about subdomains

function audit() {
	domain=$1
	subdomain=$2
	query=$(dig $2.$1 | grep -A1 'ANSWER SECTION:')
	#echo $query
	#echo $query | awk '{split($0, result, " "); print result}'`
	resultarray=($(awk -F' '  '{$1=$1} 1' <<< "${query}"))
	record=${resultarray[-2]}
	ip=${resultarray[-1]}
	echo "The subdomain $subdomain is a $record record and points to $ip"
	return 0
}

audit $1 $2

