#!/usr/bin/env bash
#Install certbot on HAProxy

#update snapd
sudo snap install core; sudo snap refresh core

#remove certbot-auto and any certbot OS packages
sudo apt-get remove certbot

#install certbot
sudo snap install --classic certbot

#prepare the certbot command
sudo ln -s /snap/bin/certbot /usr/bin/certbot

#stop HAProxy
sudo service haproxy stop

#install certificate
sudo certbot certonly --standalone
#enter domain name

# Location of certificates: /etc/letsencrypt/live/<domain-name>/fullchain.pem
# Location of private keys: /etc/letsencrypt/live/<domain-name>/privkey.pem

# Concatenate the certificate with the private key: this will be used by haproxy
# Go on the folder with your letencrypt keys that you just generated
cd /etc/letsencrypt/live/

# You might want to do be run all these commands as root if you're getting permission denied
sudo bash # run as root

cd <domain-name>
cat cert.pem privkey.pem > all.pem

# Use this all.pem file in your haproxy configuration. Refer to 1-haproxy_ssl_termination file.

# Add the following line on frontend to redirect http to https if needed
http-request redirect scheme https unless { ssl_fc }

# Restart haproxy, and you're good to go!
sudo service haproxy start # or restart

#####ignore all these, check https://markontech.com/linux/install-lets-encrypt-ssl-on-haproxy/

