#!/usr/bin/env bash
# install and configure nginx server

sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
sudo ufw enable
#sudo echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html
echo "Hello World!" > index.html
sudo service nginx restart

