#!/usr/bin/env bash
# configure ngin server

# sudo systemctl start nginx
sudo apt-get -y install nginx
sudo service nginx start
sudo ufw allow 'Nginx HTTP'
echo "Hello World\n" | sudo tee /var/www/html/index.nginx-debian.html
sudo service nginx restart

