#!/usr/bin/env bash
# install nginx and configure redirect

sudo apt update
sudo apt install nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22
sudo ufw --force enable
echo "Hello World!" | sudo tee /var/www/html/index.html

#redirect
sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#sudo service nginx restart

