#!/usr/bin/env bash
# install nginx and configure redirect

sudo apt-get update
sudo apt-get install -y nginx
sudo ufw allow 'Nginx HTTP'
sudo ufw allow 22
sudo ufw --force enable
echo "Hello World!" | sudo tee /var/www/html/index.html

#permissions
#sudo chown -R $USER:$USER /var/www/html
sudo chmod -R 755 /var/www

#redirect
#sudo sed -i '52 a\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

#sudo sed -i -f - /etc/nginx/sites-available/default << EOF
#/^\tserver_name/ a\\ 
#        location /redirect_me {\\
#        	rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\\
#	}\\
#EOF

#prefer the line below
sudo sed -i '/^\tserver_name/a \\n\tlocation /redirect_me {\n\t\trewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;\n\t}\n' /etc/nginx/sites-available/default

#try
#sed -i '37i\rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-enabled/default


#restart server
sudo service nginx restart

