#!/usr/bin/env bash
#install and configure HAProxy on server lb-01

#install scripts
sudo apt-get update
sudo apt-get install -y haproxy

#config script
echo -e "\n\nfrontend http\n\tbind *:80\n\tmode http\n\n\tdefault_backend web-backend\n\nbackend web-backend\n\tbalance roundrobin\n\tserver 804-web-01 3.233.229.162:80 check\n\tserver 804-web-02 44.197.235.170:80 check\n" | sudo tee -a /etc/haproxy/haproxy.cfg

#restart HAProxy
sudo service haproxy restart
