#!/usr/bin/env bash
#make nginx listen to port 80
#sudo sed -i 's/8080/80/g' /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
sudo service nginx restart
sudo pkill nginx
