#!/usr/bin/env bash
#script that creates a files containing its PID,
#displays To infinity and beyond indefinitely,
#handles SIGTERM, SIGINT and SIGQUIT interrupts

echo "$$" > /var/run/myscript.pid

terminate(){
    rm /var/run/myscript.pid
    exit
}

while true
do
    echo "To infinity and beyond"
    sleep 2
    trap 'echo "Y U no love me?!"' SIGINT
    trap 'echo "I hate the kill command" && teminate' SIGTERM
    trap 'terminate' SIGQUIT
done

