#!/usr/bin/env bash
#script that changes text displayed upon a condition

count=1
while [ $count -le 10 ]
do
    if [ $count -eq 9]
    then
	echo "Hi"
    else
	echo "Best School"
    fi
    x=$(( count + 1 ))
done
