#!/usr/bin/env bash
#script that changes text displayed upon a condition

count=1
while [ $count -le 10 ]
do
    if [ $count -eq 10 ]
    then
	echo "Hi";
    fi
    echo "Best School"
    count=$(( count + 1 ))
done
